# Generated by Django 4.2.5 on 2023-10-17 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_type", models.CharField(max_length=20)),
                ("is_deleted", models.BooleanField()),
                (
                    "trip_category_1_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="userinfo_trip_category_1",
                        to="main.tripcategory",
                    ),
                ),
                (
                    "trip_category_2_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="userinfo_trip_category_2",
                        to="main.tripcategory",
                    ),
                ),
                (
                    "trip_category_3_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="userinfo_trip_category_3",
                        to="main.tripcategory",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("user_password", models.CharField(max_length=255)),
                ("user_type", models.CharField(max_length=20)),
                ("is_deleted", models.BooleanField()),
                (
                    "trip_category_1_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_trip_category_1",
                        to="main.tripcategory",
                    ),
                ),
                (
                    "trip_category_2_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_trip_category_2",
                        to="main.tripcategory",
                    ),
                ),
                (
                    "trip_category_3_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_trip_category_3",
                        to="main.tripcategory",
                    ),
                ),
            ],
        ),
    ]
