# Generated by Django 4.2.6 on 2023-10-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_user_type_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(max_length=20),
        ),
    ]
