<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-16 10:15
=======
# Generated by Django 4.2.5 on 2023-10-16 08:25
>>>>>>> 035b54b81cc8f3e8ff81f8f8582e000e47112d01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="trip_break_end",
            new_name="trip_time",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="trip_break_start",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="trip_closed",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="trip_last_order",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="trip_open",
        ),
        migrations.AddField(
            model_name="trip",
            name="area_m_id",
            field=models.ForeignKey(
<<<<<<< HEAD
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.aream"
=======
                db_column="area_m_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.aream",
>>>>>>> 035b54b81cc8f3e8ff81f8f8582e000e47112d01
            ),
        ),
    ]
