# Generated by Django 4.2.6 on 2023-10-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripcomment",
            name="trip_commnet_time",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
