# Generated by Django 4.2.6 on 2023-10-16 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="trip_break_end",
            new_name="trip_time",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="trip_break_start",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="trip_closed",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="trip_last_order",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="trip_open",
        ),
        migrations.AddField(
            model_name="trip",
            name="area_m_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.aream"
            ),
        ),
    ]
