# Generated by Django 4.2.5 on 2023-10-16 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
        ("board", "0002_rename_trip_break_end_trip_trip_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="area_m_id",
        ),
        migrations.AddField(
            model_name="trip",
            name="area_m",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="main.aream"
            ),
        ),
    ]
