# Generated by Django 4.2.6 on 2023-10-19 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_alter_tripcomment_trip_commnet_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tripcomment",
            old_name="trip_commnet_time",
            new_name="trip_comment_time",
        ),
    ]
