# Generated by Django 4.2.5 on 2023-10-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_remove_trip_trip_break_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
# Generated by Django 4.2.5 on 2023-10-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_remove_trip_trip_break_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
