# Generated by Django 4.2.5 on 2023-10-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_trip_is_deleted'),
        ('board', '0003_remove_trip_area_m_id_trip_area_m'),
    ]

    operations = [
    ]
