# Generated by Django 4.2.5 on 2023-10-16 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0004_merge_20231016_1950"),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name="trip",
    #         name="area_m_ID",
    #     ),
    # ]
