# Generated by Django 4.2.5 on 2023-10-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0005_remove_trip_area_m_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="trip_time",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
