# Generated by Django 4.2.5 on 2023-10-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0006_trip_trip_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="review_image1",
            field=models.ImageField(default="", upload_to="image"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="review_image2",
            field=models.ImageField(default="", upload_to="image"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="review_image3",
            field=models.ImageField(default="", upload_to="image"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="review_image4",
            field=models.ImageField(default="", upload_to="image"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="review_image5",
            field=models.ImageField(default="", upload_to="image"),
            preserve_default=False,
        ),
    ]
