# Generated by Django 4.2.5 on 2023-10-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0007_review_review_image1_review_review_image2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_image1",
            field=models.ImageField(upload_to="review_image"),
        ),
        migrations.AlterField(
            model_name="review",
            name="review_image2",
            field=models.ImageField(upload_to="review_image"),
        ),
        migrations.AlterField(
            model_name="review",
            name="review_image3",
            field=models.ImageField(upload_to="review_image"),
        ),
        migrations.AlterField(
            model_name="review",
            name="review_image4",
            field=models.ImageField(upload_to="review_image"),
        ),
        migrations.AlterField(
            model_name="review",
            name="review_image5",
            field=models.ImageField(upload_to="review_image"),
        ),
    ]
