# Generated by Django 4.2.5 on 2023-10-17 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0009_alter_review_review_image1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewcomment",
            old_name="review_commnet_time",
            new_name="review_comment_time",
        ),
    ]
